---
deployment:
  tasks:
    # Set path variables
    - export DEPLOYPATH=/itss/home/openhard/ruby/website_jekyll
    - export RUBYVENVPATH=/itss/home/openhard/rubyvenv/ruby/3.4/bin/activate
    # Move into git repo
    - cd DEPLOYPATH
    # Activate ruby virtual environment
    - source RUBYVENVPATH
    # Build the files in the repo using jekyll
    - /itss/home/openhard/rubyvenv/ruby/3.4/bin/jekyll build
